.circleci/config.yml
CONTRIBUTING.md
README.md
package-lock.json
package.json

Introduces automated release flow using [semantic-release](https://github.com/semantic-release/semantic-release). With additionally hacked beta-pre-releases for pull requests. 
<hr /><p><time>(5/9/2019, 1:05:31 PM)</date> Pre-released as <code>@cotype/core@1.0.1-beta.41c621d</code></p>

Semantic release

---

src/content/rest/describe.ts
src/persistence/adapter/knex/KnexContent.ts

<hr /><p><time>(5/10/2019, 1:51:19 PM)</date> Pre-released as <code>@cotype/core@1.1.0-beta.02a9c84</code></p>

feat(server): allow multiple values for comparison operators eq/nq

---

src/content/rest/filterRefData.ts

Nested Joins also available for List Type

feat(server): nested Joins for lists

---

src/content/rest/describe.ts

<hr /><p><time>(5/13/2019, 4:55:39 PM)</date> Pre-released as <code>@cotype/core@1.6.1-beta.012ab14</code></p>

fix(server: openapi): remove typo from openapi

---

README.md
src/index.ts

This is a first re-iteration over the readme. 
My goal is to provide a good starting point which we can extend. 
I did not take all the time to provide all options, but only started with the required ones, as written in https://github.com/cotype/core/issues/13, i propose to add/refine the readme step by step in the future.
PTAL @cotype/maintainers 
Here is a non-diff preview of [the new README.md](https://github.com/cotype/core/blob/docs/be-more-welcoming/README.md)
<hr /><p><time>(5/18/2019, 5:02:28 PM)</date> Pre-released as <code>@cotype/core@1.7.4-beta.00916d9</code></p>

Be more welcoming

---

README.md
src/api/swaggerUi.ts
src/content/rest/index.ts
src/index.ts

Make swaggerUi redirects and displayed work correctly under different basePath situations.
<hr /><p><time>(5/27/2019, 6:05:52 PM)</date> Pre-released as <code>@cotype/core@1.12.2-beta.36fca88</code></p>

Stabilize cms base url

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/Edit/elements/MediaInput.tsx
client/src/Media/Topbar.tsx
client/src/Media/UploadField.tsx
client/src/Media/UploadZone.tsx
client/src/Media/__tests__/UploadZone.test.tsx
client/src/Media/createValidator.ts
client/src/Media/useValidation.ts
client/typings/untyped-modules.d.ts

Moving parallel uploads and presigned API into follow up PRs
<hr /><p><time>(6/14/2019, 8:48:03 AM)</date> Pre-released as <code>@cotype/core@1.14.6-beta.ad54ae6</code></p>

Update dropzone and upload libraries

---

client/src/Edit/elements/TextInput.tsx
client/src/Edit/elements/__tests__/textInput.test.ts
typings/models.d.ts

- possibility to add regex validation to text input 
- custom error message (for regex) can set with regexError

feat(validation): add regex validation for textInput

---

client/src/Edit/elements/PositionInput.tsx
src/persistence/adapter/knex/KnexContent.ts

<hr /><p><time>(6/27/2019, 5:14:45 PM)</date> Pre-released as <code>@cotype/core@1.16.4-beta.2cdfb0f</code></p>

fix(server): setPosition if positionField is empty

---

client/src/Edit/elements/ReferenceInput.tsx
client/src/Edit/elements/__tests__/referenceInput.test.ts

don't validate not required references
<hr /><p><time>(7/18/2019, 11:18:28 AM)</date> Pre-released as <code>@cotype/core@1.18.2-beta.2212197</code></p>

fix(validation): ReferenceInput and update tests

---

client/src/Edit/RichTextLinkModal.tsx
client/src/Media/Details/index.tsx
src/content/convert.ts
src/model/extractRefs.ts
src/persistence/removeDeprecatedData.ts

<hr /><p><time>(7/22/2019, 5:11:22 PM)</date> Pre-released as <code>@cotype/core@1.20.0-beta.d60cffd</code></p>

feat(client): Allow to Link Media in RichText Fields

---

client/src/Edit/Form.tsx
client/src/Edit/elements/ReferenceInput.tsx
client/src/Header/Search.tsx
client/src/common/Autocomplete.tsx
client/src/common/ResultItem.tsx
client/src/utils/__tests__/orderSearchResults.test.ts
client/src/utils/orderSearchResults.ts
src/model/__tests__/extractMatch.test.ts
src/model/extractMatch.ts
src/model/rankingFunctions/__tests__/rankingFunctions.test.ts
src/model/rankingFunctions/__tests__/text.ts
src/model/rankingFunctions/bm25.ts
src/model/rankingFunctions/ratcliffObershelp.ts
src/persistence/ContentPersistence.ts
typings/entities.d.ts

Highlight query match in result items and show description, if available. 
<hr /><p><time>(7/29/2019, 10:20:27 AM)</date> Pre-released as <code>@cotype/core@1.21.0-beta.fcfd32e</code></p>

feat: make search results a little easier on the eyes

---

client/src/Media/Gallery.tsx
client/src/Media/Topbar.tsx
client/src/Media/UploadZone.tsx
client/src/Media/__tests__/Topbar.test.tsx
client/src/Media/index.tsx
src/persistence/adapter/knex/KnexContent.ts

<hr /><p><time>(8/2/2019, 3:02:36 PM)</date> Pre-released as <code>@cotype/core@1.24.4-beta.4056123</code></p>

fix(client): Media Center Filters should rerender Gallery

---

src/content/rest/__tests__/joins.test.ts
src/persistence/ContentPersistence.ts
src/persistence/adapter/knex/KnexContent.ts

<hr /><p><time>(8/5/2019, 1:04:14 PM)</date> Pre-released as <code>@cotype/core@1.24.7-beta.b88b739</code></p>

fix(server): also add _url's to refs which are inside content refs

---

client/src/Edit/elements/MapInput.tsx
cypress/integration/settings.spec.ts
cypress/pages/lists/Roles.ts
src/index.ts
typings/models.d.ts

The value you want to display to the user is not necessary the value you want to store as the value in the map. 
<hr /><p><time>(8/8/2019, 9:54:45 AM)</date> Pre-released as <code>@cotype/core@1.27.0-beta.e2f6663</code></p>

feat(client): allow the use of objects with label and value for a map value

---

src/model/settings.ts

<hr /><p><time>(8/9/2019, 11:29:24 AM)</date> Pre-released as <code>@cotype/core@1.28.0-beta.a77ef15</code></p>

feat(client): validate e-mail address in user settings

---

src/media/storage/FsStorage.ts

<hr /><p><time>(9/10/2019, 1:32:55 PM)</date> Pre-released as <code>@cotype/core@1.30.3-beta.1ae93d5</code></p>

fix: don't upwards resolve file paths

---

client/src/Edit/elements/ReferenceInput.tsx
src/api/oapi.ts
src/content/convert.ts
src/content/rest/describe.ts
src/content/routes.ts
src/model/extractValues.ts
src/persistence/ContentPersistence.ts
src/persistence/adapter/knex/KnexContent.ts
typings/entities.d.ts

<hr /><p><em><date>[2020-04-03T09:13:15.182Z]</date></em> Pre-released:<br /><code>@cotype/core@1.35.5-feature-ExternalDataSource.3dc2be0</code></p>

fix(server): DataSources

---

client/src/Edit/elements/lists/block/Input.tsx
client/src/Edit/elements/lists/inline/Input.tsx

<hr /><p><em><date>[2020-05-06T12:09:47.084Z]</date></em> Pre-released:<br /><code>@cotype/core@1.36.5-feature-fixExternal.fb3a262</code></p>

fix(client): Fix ExternalDataSource in Lists

---

README.md
client/src/List/IFrameView.tsx
client/src/List/index.tsx
demo/models.ts
demo/navigation.json
src/content/rest/describe.ts
src/content/rest/routes.ts
src/model/builder.ts
src/session.ts
typings/entities.d.ts
typings/models.d.ts

<hr /><p><em><date>[2020-04-28T11:48:20.244Z]</date></em> Pre-released:<br /><code>@cotype/core@1.37.0-feature-iframePage.fb8d523</code></p>

feat(core): IFrame View in CMS

---

README.md
client/src/Edit/elements/OptionsInput.tsx
client/src/Edit/elements/OptionsOutput.tsx

<hr /><p><em><date>[2020-05-25T11:05:46.147Z]</date></em> Pre-released:<br /><code>@cotype/core@1.38.1-feature-CMSFixes.a3d3414</code></p>

Fix: Select Field with label/value

---

client/src/Edit/elements/SlugInput.tsx

<hr /><p><em><date>[2020-06-23T14:58:43.675Z]</date></em> Pre-released:<br /><code>@cotype/core@1.39.2-feature-fixSlugDuplicate.534592c</code></p>

fix(client): Slug editable in Duplicate
